# tasks file
---
- name: install dependencies
  ansible.builtin.apt:
    name: "{{ pip_dependencies }}"
    state: "{{ apt_install_state | default('latest') }}"
    update_cache: true
    cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"
  tags:
    - configuration
    - pip
    - pip-dependencies

- name: create (download) directory
  ansible.builtin.file:
    path: "{{ pip_download_path }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  tags:
    - configuration
    - pip
    - pip-directory

- name: get python version  # noqa risky-shell-pipe
  ansible.builtin.shell: >
    python{{ pip_python_version_major | string }} --version 2>&1 | awk '{print $2}'
  register: _python_version
  changed_when: false
  tags:
    - configuration
    - pip
    - pip-get-python-version

- name: get download url
  tags:
    - configuration
    - pip
    - pip-get-download-url
  block:
    - name: get download url (2.6)
      ansible.builtin.set_fact:
        pip_download_url: 'https://bootstrap.pypa.io/pip/2.6/get-pip.py'
      when:
        - _python_version.stdout is version('2.6', '>=')
        - _python_version.stdout is version('2.7', '<')

    - name: get download url (2.7)
      ansible.builtin.set_fact:
        pip_download_url: 'https://bootstrap.pypa.io/pip/2.7/get-pip.py'
      when:
        - _python_version.stdout is version('2.7', '>=')
        - _python_version.stdout is version('2.8', '<')

    - name: get download url (3.2)
      ansible.builtin.set_fact:
        pip_download_url: 'https://bootstrap.pypa.io/pip/3.2/get-pip.py'
      when:
        - _python_version.stdout is version('3.2', '>=')
        - _python_version.stdout is version('3.3', '<')

    - name: get download url (3.3)
      ansible.builtin.set_fact:
        pip_download_url: 'https://bootstrap.pypa.io/pip/3.3/get-pip.py'
      when:
        - _python_version.stdout is version('3.3', '>=')
        - _python_version.stdout is version('3.4', '<')

    - name: get download url (3.4)
      ansible.builtin.set_fact:
        pip_download_url: 'https://bootstrap.pypa.io/pip/3.4/get-pip.py'
      when:
        - _python_version.stdout is version('3.4', '>=')
        - _python_version.stdout is version('3.5', '<')

    - name: get download url (3.5)
      ansible.builtin.set_fact:
        pip_download_url: 'https://bootstrap.pypa.io/pip/3.5/get-pip.py'
      when:
        - _python_version.stdout is version('3.5', '>=')
        - _python_version.stdout is version('3.6', '<')

    - name: get download url (3.6)
      ansible.builtin.set_fact:
        pip_download_url: 'https://bootstrap.pypa.io/pip/3.6/get-pip.py'
      when:
        - _python_version.stdout is version('3.6', '>=')
        - _python_version.stdout is version('3.7', '<')

    - name: get download url (3.7)
      ansible.builtin.set_fact:
        pip_download_url: 'https://bootstrap.pypa.io/pip/3.7/get-pip.py'
      when:
        - _python_version.stdout is version('3.7', '>=')
        - _python_version.stdout is version('3.8', '<')

    - name: get download url (latest)
      ansible.builtin.set_fact:
        pip_download_url: 'https://bootstrap.pypa.io/pip/get-pip.py'
      when: _python_version.stdout is version('3.8', '>=')

- name: download (latest) pip
  ansible.builtin.get_url:
    url: "{{ pip_download_url }}"
    dest: "{{ pip_download_path }}/{{ pip_download_url | basename }}-{{ pip_python_version_major | string }}"
    owner: root
    group: root
    mode: 0644
    force: true
  register: _download_latest
  tags:
    - configuration
    - pip
    - pip-pip-download

- name: install (latest) pip (setuptools and wheel)
  ansible.builtin.command: >
    python{{ pip_python_version_major | string }} {{ _download_latest.dest }}
  when: _download_latest is changed
  changed_when: true
  tags:
    - configuration
    - pip
    - pip-pip-install
