# tasks file for pip
---
- name: install dependencies
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: true
    cache_valid_time: 3600
  with_items: pip_dependencies
  tags:
    - configuration
    - pip
    - pip-dependencies

- name: upgrade
  pip:
    name: pip
    state: latest
  when: pip_self_update
  tags:
    - configuration
    - pip
    - pip-upgrade
