# tasks file for pip
---
- name: install dependencies
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: true
    cache_valid_time: 3600
  with_items: pip_dependencies
  tags:
    - configuration
    - pip
    - pip-dependencies

- name: create (download) directory
  file:
    path: "{{ pip_download_path }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  tags:
    - configuration
    - pip
    - pip-download
    - pip-download-directory

- name: download (latest)
  get_url:
    url: "{{ item }}"
    dest: "{{ pip_download_path }}/{{ item | basename }}"
    owner: root
    group: root
    mode: 0644
    force: true
  register: download_latest
  with_items: pip_download_urls
  tags:
    - configuration
    - pip
    - pip-download
    - pip-download-latest

- name: install (latest)
  command: "python {{ item.dest }}"
  with_items: download_latest.results
  when: item.changed
  tags:
    - configuration
    - pip
    - pip-download
    - pip-download-install-latest
