# tasks file for pip
---
- name: install dependencies
  apt:
    name: "{{ item }}"
    state: "{{ apt_install_state | default('latest') }}"
    update_cache: true
    cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"
  with_items: "{{ pip_dependencies }}"
  tags:
    - configuration
    - pip
    - pip-dependencies

- name: create (download) directory
  file:
    path: "{{ pip_download_path }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  tags:
    - configuration
    - pip
    - pip-directory

- name: download (latest) pip
  get_url:
    url: "{{ pip_download_url }}"
    dest: "{{ pip_download_path }}/{{ pip_download_url | basename }}"
    owner: root
    group: root
    mode: 0644
    force: true
  register: _download_latest
  tags:
    - pip-pip-download

- name: install (latest) pip (setuptools and wheel)
  command: python {{ _download_latest.dest }}
  when: _download_latest | changed
  tags:
    - pip-pip-install
