# tasks file for pip
---
- name: install dependencies
  apt:
    name: "{{ item }}"
    state: "{{ apt_install_state | default('latest') }}"
    update_cache: true
    cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"
  with_items: "{{ pip_dependencies }}"
  tags:
    - configuration
    - pip
    - pip-dependencies

- name: create (download) directory
  file:
    path: "{{ pip_download_path }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  tags:
    - configuration
    - pip
    - pip-directory

- include: setuptools.yml
  tags:
    - configuration
    - pip
    - pip-setuptools

- include: pip.yml
  tags:
    - configuration
    - pip
    - pip-pip
