# tasks file for pip
---
- name: install dependencies
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: true
    cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"
  with_items: pip_dependencies
  tags:
    - configuration
    - pip
    - pip-dependencies

- name: create (download) directory
  file:
    path: "{{ pip_download_path }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  tags:
    - configuration
    - pip
    - pip-download
    - pip-download-directory

- name: download (latest) setuptools
  get_url:
    url: "{{ pip_download_url }}"
    dest: "{{ pip_download_path }}/{{ pip_download_url | basename }}"
    owner: root
    group: root
    mode: 0644
    force: true
  register: download_latest
  tags:
    - configuration
    - pip
    - pip-download
    - pip-download-latest-setuptools

- name: install (latest) setuptools
  command: "python {{ download_latest.dest }}"
  when: download_latest | changed
  tags:
    - configuration
    - pip
    - pip-install
    - pip-install-latest-setuptools

- name: install pip
  easy_install:
    name: pip
  tags:
    - configuration
    - pip
    - pip-install
    - pip-install-pip

- name: update pip
  pip:
    name: pip
    state: latest
  tags:
    - configuration
    - pip
    - pip-update
    - pip-update-pip
