# tasks file for pip
---
- name: install dependencies
  apt:
    name: "{{ pip_dependencies }}"
    state: "{{ apt_install_state | default('latest') }}"
    update_cache: true
    cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"
  tags:
    - configuration
    - pip
    - pip-dependencies

- name: create (download) directory
  file:
    path: "{{ pip_download_path }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  tags:
    - configuration
    - pip
    - pip-directory

- name: get python version
  shell: >
    python{{ pip_python_version | string }} --version 2>&1 | awk '{print $2}'
  register: _python_version
  changed_when: false
  tags:
    - configuration
    - pip
    - pip-get-python-version

- block:

    - name: get download url (2.6)
      set_fact:
        pip_download_url: 'https://bootstrap.pypa.io/2.6/get-pip.py'
      when:
        - _python_version.stdout is version('2.6', '>=')
        - _python_version.stdout is version('2.7', '<')

    - name: get download url (2.7)
      set_fact:
        pip_download_url: 'https://bootstrap.pypa.io/2.7/get-pip.py'
      when:
        - _python_version.stdout is version('2.7', '>=')
        - _python_version.stdout is version('2.8', '<')

    - name: get download url (3.2)
      set_fact:
        pip_download_url: 'https://bootstrap.pypa.io/3.2/get-pip.py'
      when:
        - _python_version.stdout is version('3.2', '>=')
        - _python_version.stdout is version('3.3', '<')

    - name: get download url (3.3)
      set_fact:
        pip_download_url: 'https://bootstrap.pypa.io/3.3/get-pip.py'
      when:
        - _python_version.stdout is version('3.3', '>=')
        - _python_version.stdout is version('3.4', '<')

    - name: get download url (3.4)
      set_fact:
        pip_download_url: 'https://bootstrap.pypa.io/3.4/get-pip.py'
      when:
        - _python_version.stdout is version('3.4', '>=')
        - _python_version.stdout is version('3.5', '<')

    - name: get download url (3.5)
      set_fact:
        pip_download_url: 'https://bootstrap.pypa.io/3.5/get-pip.py'
      when:
        - _python_version.stdout is version('3.5', '>=')
        - _python_version.stdout is version('3.6', '<')

    - name: get download url (latest)
      set_fact:
        pip_download_url: 'https://bootstrap.pypa.io/get-pip.py'
      when: _python_version.stdout is version('3.6', '>=')

  tags:
    - configuration
    - pip
    - pip-get-download-url

- debug:
    msg: "{{ pip_download_url }}"

- name: download (latest) pip
  get_url:
    url: "{{ pip_download_url }}"
    dest: "{{ pip_download_path }}/{{ pip_download_url | basename }}-{{ pip_python_version | string }}"
    owner: root
    group: root
    mode: 0644
    force: true
  register: _download_latest
  tags:
    - configuration
    - pip
    - pip-pip-download

- name: install (latest) pip (setuptools and wheel)
  command: >
    python{{ pip_python_version | string }} {{ _download_latest.dest }}
  when: _download_latest is changed
  tags:
    - configuration
    - pip
    - pip-pip-install
