# tasks file
---
- name: install native
  ansible.builtin.import_tasks: install-native.yml
  when: pip_install_method == 'native'
  tags:
    - configuration
    - pip
    - pip-install-native

- name: install pip
  ansible.builtin.import_tasks: install-get-pip.yml
  when: pip_install_method == 'get-pip'
  tags:
    - configuration
    - pip
    - pip-install-get-pip

- name: install additional
  ansible.builtin.apt:
    name: "{{ pip_install }}"
    state: "{{ apt_install_state | default('latest') }}"
  tags:
    - configuration
    - pip
    - pip-install
    - pip-install-additional

- name: verify
  ansible.builtin.command: >
    pip --version
  changed_when: false
  tags:
    - configuration
    - pip
    - pip-install
    - pip-install-verify
