# tasks file for pip
---
- name: download (latest) setuptools
  get_url:
    url: "{{ pip_download_url }}"
    dest: "{{ pip_download_path }}/{{ pip_download_url | basename }}"
    owner: root
    group: root
    mode: 0644
    force: true
  register: download_latest
  tags:
    - pip-setuptools-download

- name: install (latest) setuptools
  command: python {{ download_latest.dest }}
  when: download_latest | changed
  tags:
    - pip-setuptools-install

- name: find (tmp) setuptools files
  command: find . -type f -name 'setuptools-*.zip'
  register: tmp_setuptools_files
  changed_when: tmp_setuptools_files.stdout_lines | length > 0
  tags:
    - pip-setuptools-cleanup

- name: remove (tmp) setuptools files
  file:
    path: "{{ item }}"
    state: absent
  with_items: "{{ tmp_setuptools_files.stdout_lines }}"
  tags:
    - pip-setuptools-cleanup
